### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by RetroGamer02** [RetroGamer02/dosbox-3ds#1]
- [x] Fix VGA and SVGA Modes in Bitshift Test Branch
- [ ] Find source of occasional audio distortion and fix it.
- [ ] Use Invariant Multiply instead of Division where possible.
- [ ] Test more games and other software.
- [ ] Try to take the 286 CPU Cores from DOSBox-X and make them work in DOSBox-3DS.
- [ ] See if RENDER_StartLine is thread safe needs heavy testing and probably tweaks to avoid graphics corruption mostly on first few lines.

SVGA Mode seems to just be a lack of ram probably works on New 3DS.
